name: Run manually specific spec for MVC TODO

on:
  workflow_dispatch:
    inputs:
      CYPRESS_RECORD_KEY:
        description: 'Cypress cloud project record key'
        default: '46216992-157f-44dc-b1db-3f975d019580'
        required: true
      CYPRESS_PROJECT_ID:
        description: 'Cypress cloud project id'
        default: '1gn2b3'
        required: true
      specPath:
        type: choice
        required: true
        description: Choose spec path
        options:
          - to_do_app.spec.js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - run: npm install
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ${{ github.workspace }}
          install-command: npm install
          browser: chrome
          parallel: false
          config-file: ./cypress.config.js
          spec: ${{ github.workspace }}/cypress/to_do_app/tests/e2e/${{ github.event.inputs.specPath }}
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ github.event.inputs.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ github.event.inputs.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}